In [71]:
import pandas as pd
import numpy as np

A) First NumPy Array

In [72]:

baseball = [180, 185, 190, 195, 200, 170, 210, 175, 165, 190]

np_baseball = np.array(baseball)

print(np_baseball)
print()
print(type(np_baseball))

[180 185 190 195 200 170 210 175 165 190]

<class 'numpy.ndarray'>


B) Baseball players' height

In [67]:
#Sample list
height_in = [63, 70, 61, 68, 72, 68, 69, 70, 64, 68]

np_height_in = np.array(height_in)

print(np_height_in)

#Ensuring the type
print(type(np_height_in))

#Converting the heights in inches to meters
np_height_m = np_height_in*0.0254

#Printing result array
print(np_height_m)

[63 70 61 68 72 68 69 70 64 68]
<class 'numpy.ndarray'>
[1.6002 1.778  1.5494 1.7272 1.8288 1.7272 1.7526 1.778  1.6256 1.7272]


-------------------------------------------------------------------------------------------------------------------
C) Baseball player's BMI

In [68]:
#Sample weight list
weight_lbs = [120, 160, 170, 180, 110, 100, 110, 120, 130, 140]
weight_lbs = np.array(weight_lbs)

print("Weight in pounds =", weight_lbs)
print()
print("Height in metres =", np_height_m)

np_weight_kg = weight_lbs*0.453592
print()
print("Weight in kg =", np_weight_kg)

bmi = np_weight_kg / (np_height_m ** 2)
print()
print("BMI =", bmi)



Weight in pounds = [120 160 170 180 110 100 110 120 130 140]

Height in metres = [1.6002 1.778  1.5494 1.7272 1.8288 1.7272 1.7526 1.778  1.6256 1.7272]

Weight in kg = [54.43104 72.57472 77.11064 81.64656 49.89512 45.3592  49.89512 54.43104
 58.96696 63.50288]

BMI = [21.25681047 22.9573553  32.12086295 27.36860318 14.91851672 15.20477954
 16.2439804  17.21801648 22.31420185 21.28669136]


-------------------------------------------------------------------------------------------------------------------
D) Lightweight baseball players

In [69]:
light = bmi < 21
print(light)
print()
print(light[4])

[False False False False  True  True  True  True False False]

True


-------------------------------------------------------------------------------------------------------------------
E) NumPy Side Effects

np.array([True, 1, 2]) + np.array([3, 4, False])

This would perform concatenation on the two arrays so i believe it would look something like this:
[True, 1, 2, 3, 4, False]

-------------------------------------------------------------------------------------------------------------------
F) Blend it all together

In [70]:
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]

np_positions = np.array(positions)
np_heights = np.array(heights)

gk_heights = np_heights[np_positions == 'GK']

other_heights = np_heights[np_positions != 'GK']

print("Median height of goalkeepers:", np.median(gk_heights))

print("Median height of other players:", np.median(other_heights))


Median height of goalkeepers: 191.0
Median height of other players: 184.0
